name: java-system-config
ruletype: standard
criticality: medium
cloud: 100
container: 100
filetype: java$
target: line
type: regex
defaultpattern: (System.)%s\(
advice: Review usage of environment variables and system properties and externalize.
effort: 3
readiness: 10
category: config
tags:
  - value: config
  - value: configuration
patterns:
  - value: getenv
  - value: getProperty
  - value: setProperty
  - value: setProperties
profiles:
  - value: cloud-suitability
  - value: Azure Spring Apps
