name: java-properties-eureka-client-configs
ruletype: standard
criticality: medium
level: Info
cloud: 100
container: 100
filetype: properties$
target: line
type: regex
advice: The application is using eureka and setting the connection string
category: eureka
effort: 0
tags:
  - value: eureka
patterns:
  - value: (^|\s)eureka\.client\.(service-url|serviceUrl)
profiles:
  - value: Azure Spring Apps