name: java-properties-eureka-client-configs
ruletype: standard
criticality: medium
level: Info
cloud: 50
container: 50
filetype: properties$
target: line
type: regex
advice: The application is using eureka and setting the connection string
category: eureka
effort: 0
tags:
  - value: eureka
patterns:
  - value: (^|\s)eureka\.client\.(service-url|serviceUrl)