name: java-yaml-eureka-client-configs
ruletype: standard
criticality: medium
cloud: 100
container: 100
filetype: (yaml$|yml$)
target: contents
type: yamlpath
level: Info
advice: The application is using eureka and setting the connection string
category: eureka
effort: 0
tags:
  - value: eureka
  - value: configuration
patterns:
  - value: $.eureka.client["service-url","serviceUrl"]
profiles:
  - value: Azure Spring Apps