#qc1
name: dotnet-ISAPI-Filters-config
ruletype: standard
filetype: config$
target: file
type: xpath
advice: Windows and IIS server dependency. Not supported in .netCore targeting linux.
category: unsupported-iis-module
effort: 1000
readiness: 10
patterns:
- value: /configuration/system.webServer/isapiFilters[1]
#- <configuration><system.webServer><isapiFilters
tags:
- value: iis-module
# Mostly a challenge if moving to .NetCore
profiles:
- value: netcore