name: Docker Image CI

# on:
#   release:
#     types: [created]

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  # push:
  #   branches: ['add_docker_build_action']

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download release asset
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        version: latest
        file: csa-l
        target: csa-l
        token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ghcr
      uses: docker/login-action@v2 
      with:
        registry: ${{ vars.DOCKER_HUB_URL }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Build and push to ghcr
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ vars.DOCKER_HUB_URL }}/${{ secrets.DOCKER_HUB_USERNAME }}/csa:experimental
