name: kube-config
filetype: (yaml$)
target: line
type: regex
defaultpattern: (%s)
advice: Kubernetes Config
patterns:
  - value: .*kind:\s.*Deployment.*
  - value: .*kind:\s.*Service.*
  - value: .*kind:\s.*Pod.*
  - value: .*kind:\s.*Policy.*
readiness: 9
effort: 0
category: platform
tags:
  - value: kubernetes
  - value: platform
  - value: container
profiles:
  - value: compass-discovery
  - value: cloud-suitability
