#qc1
name: config-security
ruletype: standard
filetype: config$
target: file
type: xpath
advice: Use of generated machine keys is problematic
effort: 100
readiness: 100
category: security
tags:
- value: auto-gen-key
patterns:
- value: /configuration/system.web/machineKey[contains(@validationKey, "AutoGenerate") or contains(@decryptionKey, "AutoGenerate")]

##validationKey="AutoGenerate"
##decryptionKey="AutoGenerate"
profiles:
- value: cloud-suitability