name: dotnet-file-based-config
ruletype: standard
criticality: medium
cloud: 50
container: 50
filetype: cs
target: line
type: regex
defaultpattern: .*%s.*
advice: Externalize configuration to environment or use ConfigMap as file-mount into a K8S pod
effort: 10
readiness: 3
category: env-config
tags:
- value: env-config
patterns:
- value: .AddJsonFile\("
#- Configuration = new Configuration().AddJsonFile("config.json")
profiles:
- value: cloud-suitability