name: java-jvm-runtimeConfigProps
ruletype: standard
cloud: 50
container: 50
filetype: java$
target: line
type: regex
defaultpattern: ^.*import(\s*|=")%s.*$
advice: Do not change these properties at runtime in application code
recipes:
effort: 50
readiness: 0
category: config
tags:
- value: config
patterns:
- value: javax.xml.soap.SOAPFactory
  tag: soap
- value: javax.xml.parsers.DocumentBuilderFactory
  tag: xml-parser
- value: javax.xml.parsers.SAXParserFactory
  tag: xml-parser


#- import javax.net.ssl.keyStore
#- import javax.net.ssl.keyStoreType
#- import javax.net.ssl.keyStorePassword
#- import javax.net.ssl.trustStore
#- import javax.net.ssl.trustStoreType
#- import javax.net.ssl.trustStorePassword
#- import javax.xml.soap.SOAPFactory
#- import javax.xml.parsers.DocumentBuilderFactory
#- import javax.xml.parsers.SAXParserFactory
profiles:
- value: cloud-suitability