name: tas-environment-cfenv-maven
ruletype: standard
filetype: xml$
target: line
type: regex
defaultpattern: (>.*%s<)
advice: Application appears to be using cf env library to inject environment variables provided by TAS.
effort: 1
readiness: 7
category: tas
tags:
  - value: tas
  - value: env-config
patterns:
  - value: java-cfenv-boot
profiles:
- value: tas
