name: xml-ehcache-Config
ruletype: standard
criticality: medium
cloud: 100
container: 100
filetype: xml$
target: line
type: regex
defaultpattern: (%s)
category: cache
advice: Consider external cache provider
effort: 50
readiness: 10
tags:
- value: cache
- value: ehcache
patterns:
- value: ehcache
## amq:broker
profiles:
- value: cloud-suitability