name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt install -y nodejs npm golang go-bindata musl-tools gcc-mingw-w64 build-essential
    
    - name: Install goreleaser
      run: sudo snap install goreleaser --classic
      
    - name: Build
      run: ./build.sh
    
    - name: Upload CSA artifacts
      uses: actions/upload-artifact@master
      with:
        name: csa-artifacts
        path: csa-app/dist

    - name: Upload CSA tests artifacts
      uses: actions/upload-artifact@master
      with:
        name: csa-tests-artifacts
        path: csa-app/test-exe